const { trunks } = require('../trunks')
const { second } = require('./second')

trunks.success('Hello from a {} success {}!', 'trunks', 'log')
trunks.info('Hello from a {} info {}!', 'trunks', 'log')
trunks.debug('Hello from a {} debug {}!', 'trunks', 'log')
trunks.warn('Hello from a {} warning {}!', 'trunks', 'log')
trunks.log('custom level', 'Hello from a {} custom level {}!', 'trunks', 'log')
trunks.info('Wrong number of matchers', 'test')
trunks.error(new Error('Example Error'), 'Hello from a {} error {}!', 'trunks', 'log')
trunks.info('Setting level to PROD')
trunks.setLevel('PROD')
trunks.error(new Error('this shouldnt display'), 'testing level stops stacktrace')
trunks.info('Setting level to an unsupported type')
trunks.setLevel('NOTREAL')
second.test()
trunks.setLevel('DEBUG')
trunks.success('Testing logging of {}', {"name": "test"})
trunks.info('Testing {} with different types, heres an {}', 'Logging', {"Object": "new obj"})